### ISSUE TITLE
Add possibility to override Message and MessageHandler namespace

### ISSUE THREAD

**Issue by welcoMattic** [symfony/maker-bundle#1130]
The make command that generates Message and MessageHandler doesn't provide a way to customize the namespace, by default Message are under `$rootNamespace.'\Message'` and MessageHandler under `$rootNamespace.'\MessageHandler'`

It could be nice to give to user the ability to customize those namespaces like:

`$rootNamespace.'\Messenger\Message'` and `$rootNamespace.'\Messenger\Handler'`

I see it as a new config option:

```yaml
messenger_namespaces:
    message: 'Messenger\Message'
    handler: 'Messenger\Handler'
```

It also lets user organize all Messenger related classes under an unique namespace:

```yaml
messenger_namespaces:
    message: 'Messenger'
    handler: 'Messenger'
```
