### ISSUE TITLE
configurable template paths

### ISSUE THREAD

**Issue by tacman** [symfony/maker-bundle#1135]
If the absolute path to the template is not passed to the Generator class, it defaults to looking in makerBundle's skeleton directory.

```php
        if (!file_exists($templatePath)) {
            $templatePath = __DIR__.'/Resources/skeleton/'.$templateName;
```

What I'd like to do is set a list of paths to use when looking for a  template in the config, e.g.

```yaml
maker:
    root_namespace: Foo
    template_dirs: 
          - my/templates
          - vendor/symfony/maker-bundle/src/Resources/skeleton/twig
```

This would also allow my own makers to not require hardcoding the path or overriding the generator class.  That is, if I have a make:something (MakeSomething.php), I'd like to be able to call

```php
        $generator->generateClass(
            $extensionClassNameDetails->getFullName(),
            'Something.tpl.php',
            ['use_statements' => $useStatements]
        );
```

without having to prefix the template path myself with __DIR__ . '../../skeleton/'.

Happy to do the PR if this approach seems worthwhile.  I love the maker bundle, and use my own makers all the time.
