### ISSUE TITLE
Since #1147, make:entity no longer supports properties with a custom type

### ISSUE THREAD

**Issue by tip2tail** [symfony/maker-bundle#1157]
Replicated on a fresh Symfony 6.1 installation with these package versions installed
```
symfony/maker-bundle                v1.44.0
warhuhn/chronos-doctrine            3.0.1    
```

My `doctrine.yaml` file looks like this:

```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            chronos: Warhuhn\Doctrine\DBAL\Types\ChronosDateTimeType
            chronos_date: Warhuhn\Doctrine\DBAL\Types\ChronosDateType
            chronos_datetime: Warhuhn\Doctrine\DBAL\Types\ChronosDateTimeType
            chronos_datetimetz: Warhuhn\Doctrine\DBAL\Types\ChronosDateTimeTzType
    orm:
        auto_generate_proxy_classes: true

...etc...
```

Using `make:entity`, I attempt to add a new `createdDate` field to my `User` entity.

```
root@6fde406acaf4:/var/www/xyz-docker# php bin/console make:entity User

 Your entity already exists! So let's add some new fields!

 New property name (press <return> to stop adding fields):
 > createdDate

 Field type (enter ? to see all types) [string]:
 > chronos

 Can this field be null in the database (nullable) (yes/no) [no]:
 >


In ClassSourceManipulator.php line 269:

  Symfony\Bundle\MakerBundle\Util\ClassSourceManipulator::addSetter(): Argument #2 ($type) must be of type string, nu
  ll given, called in /var/www/xyz-docker/vendor/symfony/maker-bundle/src/Util/ClassSourceManipulator.php on line 144


make:entity [-a|--api-resource] [-b|--broadcast] [--regenerate] [--overwrite] [--] [<name>]
```

If the type was `datetime` or similar this will work.  Looks like to have been caused by #1147.
