### ISSUE TITLE
make:user gives  'Cannot find the entity manager for class "App\Entity\User" ' if App\Entity is not empty

### ISSUE THREAD

**Issue by Adi-18** [symfony/maker-bundle#1158]
Replicated on a fresh Symfony 6.1 installation
symfony/maker-bundle     v1.44.0

Error:  'Cannot find the entity manager for class "App\Entity\User" '
after command 'symfony console make:user' and if there is already an Entity in App\Entity

**Comment by jrushlow** [comment]
Howdy @Adi-18 - i'm unable to replicate this locally. Can you provider a simple re-producer app that demonstrates this error?

Another thing to check out is your `doctrine.yaml` config: 

In a fresh 6.1 app, it should look something like:
```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
```

For the user entity (Using Postgres)
```php
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    ...
```

Also, at what point are you getting that error message when running the `make:user` command?
