### ISSUE TITLE
make:registration-form is noit recognizing configured built-in authenticators for autologin

### ISSUE THREAD

**Issue by thobaier** [symfony/maker-bundle#1289]
The command `make:registration-form` generates a registration form with the possibility to use a auto-login feature.

If i answer the question with yes:
`Do you want to automatically authenticate the user after registration? (yes/no) [yes]`

and have a security configuration like:

```yaml
security:
   ...
    firewalls:
       ...
        main:
            lazy: true
            provider: users_in_memory
            form_login:
                # "app_login" is the name of the route created previously
                login_path: app_login
                check_path: app_login
```

Why i get the message warning:
`No Guard authenticators found - so your user won't be automatically authenticated after registering.`
