### ISSUE TITLE
Specific namespace for different objects

### ISSUE THREAD

**Issue by samihsoylu** [symfony/maker-bundle#1344]
Imagine that you want to create a controller in different directory, and entities in another. How could you achieve this through the config?

```yaml
maker:
  root_namespace: 'App'
  controller:
    namespace: App\Application\Controller
    dir: src/Application/Controller
  entity:
    namespace: App\Domain\Entity
    dir: src/Domain/Entity
  repository:
    namespace: App\Core\Repository\Doctrine
    dir: src/Core/Repository/Doctrine
```

The keywords controller, entity, and repository are not recognised. The only allowed option is `root_namespace`.

**Comment by tg-iserv** [comment]
I'm also interested in this feature, as our project also do not use the default directory structure

**Comment by GromNaN** [comment]
The `dir` can be found from the namespace with the psr-4 autoloading rule. Therefore, only the namespace should be specified.
Would an option when launching the command be sufficient? I don't think adding configuration is in line with the philosophy of maker-bundle, which is intended to be "plug-and-play".

**Comment by tg-iserv** [comment]
I agree that the `dir` option is not necessary.
Having to specify the whole namespace each time i want to make something would be annoying therefore I would prefer a configuration option. 
You can use the current value as default and the maker-bundle would still be "plug-and-play".
The same way as the `root_namespace` which must only be set if someone does not follow the Symfony conventions.

Still I see advantages in the command option:
- it allows for using multiple directories for controllers/entities/repositories
- it can be used to create sub namespace of entities.

**Comment by Amoifr** [comment]
Hey @GromNaN! I put together a proof-of-concept in #1794 to move the discussion forward — **not meant to be merged as-is**, just a concrete base to iterate on.

Here's the approach:

- **Config-based** with sensible defaults (nothing changes if you don't configure anything):
```yaml
maker:
    namespaces:
        entity: Domain\Entity
        controller: Application\Controller
```

- **No `dir` option** — paths are derived from PSR-4 autoloading, exactly as you suggested
- **`NamespaceType` enum** to avoid magic strings in the codebase
- **Open map** (`scalarPrototype`) — users only override what they need, defaults come from the enum
- **Validation** via `Validator::validateClassName()` on each namespace value
- **10 makers updated** — all makers using the 5 main types (controller, command, entity, form, repository)

A CLI option (`--namespace`) for one-off overrides could complement this as a follow-up — would love your thoughts on whether that's worth pursuing too.

Happy to adjust the approach based on your feedback! 🙂
