### ISSUE TITLE
make:entity generates renames for every index in database when run at test env

### ISSUE THREAD

**Issue by Mortimer333** [symfony/maker-bundle#1357]
# Context:
I want to create Entities which are only present in `test` environment and database. 

# Problem
I can't see any problems from Doctrine; Entities are properly detected and only visible at tests. I've also run`APP_ENV=test php bin/console doctrine:migrations:diff`  which resulted in "No changes detected in your mapping information.". But when I run
 `APP_ENV=test php bin/console make:migration` script seems to detect that indexes have changed and tries to rename them:
```php
$this->addSql('ALTER TABLE asset RENAME INDEX idx_6caef6446ff8bf36 TO IDX_5B32F9E06FF8BF36');
$this->addSql('ALTER TABLE asset_pointer RENAME INDEX idx_93e1a0f35da1941 TO IDX_320B8BC25DA1941');
$this->addSql('ALTER TABLE asset_thumbnail_pointer RENAME INDEX idx_78a72ce1dd820f36 TO IDX_CFE38EADD820F36');
$this->addSql('ALTER TABLE asset_thumbnail_pointer RENAME INDEX idx_78a72ce1fdff2e92 TO IDX_CFE38EAFDFF2E92');
$this->addSql('ALTER TABLE cod_campaign RENAME INDEX idx_349357cc6ff8bf36 TO IDX_F2B186D6FF8BF36');
$this->addSql('ALTER TABLE cod_campaign RENAME INDEX uniq_349357ccf2613871 TO UNIQ_F2B186DF2613871');
$this->addSql('ALTER TABLE cod_campaign RENAME INDEX uniq_349357cc192bcf11 TO UNIQ_F2B186D192BCF11');
$this->addSql('ALTER TABLE cod_item RENAME INDEX uniq_36419abc3da5256d TO UNIQ_9611AC973DA5256D');
$this->addSql('ALTER TABLE cod_item RENAME INDEX idx_36419abc6ff8bf36 TO IDX_9611AC976FF8BF36');
$this->addSql('ALTER TABLE cod_item RENAME INDEX uniq_36419abc4acc9a20 TO UNIQ_9611AC974ACC9A20');
$this->addSql('ALTER TABLE cod_item RENAME INDEX idx_36419abc1919b217 TO IDX_9611AC971919B217');
$this->addSql('ALTER TABLE cod_item_subtype_item RENAME INDEX idx_cf4a0668126f525e TO IDX_B10FB62F126F525E');
$this->addSql('ALTER TABLE cod_item_subtype_item RENAME INDEX idx_cf4a0668339f0c56 TO IDX_B10FB62F339F0C56');
$this->addSql('ALTER TABLE cod_item_cube_item RENAME INDEX idx_f320717126f525e TO IDX_F72966C0126F525E');
$this->addSql('ALTER TABLE cod_item_cube_item RENAME INDEX idx_f32071718a0c1e TO IDX_F72966C018A0C1E');
$this->addSql('ALTER TABLE cod_item_pack RENAME INDEX idx_3575bc6f6ff8bf36 TO IDX_949F975E6FF8BF36');
$this->addSql('ALTER TABLE cod_item_pack RENAME INDEX uniq_3575bc6ff2613871 TO UNIQ_949F975EF2613871');
[...]
```

Interesting part is that name of the index is incorrect - idx_6caef6446ff8bf36. Correct one is just an uppercase variant of it - IDX_6CAEF6446FF8BF36 which makes me think that there is something wrong with the component responsible for detecting index change.

### Versions:
```
symfony/maker-bundle                      v1.48.0
doctrine/dbal                             3.6.2
Symfony                                   6.2.9
```

doctrine_migrations.yaml:
```yaml
doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false

when@test:
    doctrine_migrations:
        migrations_paths:
            'DoctrineMigrations\Test': '%kernel.project_dir%/migrations/test'
```
doctrine.yaml:
```yaml
doctrine:
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Main:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity/'
                prefix: 'App\Entity'
                alias: Main

when@test:
    doctrine:
        orm:
            mappings:
                Test:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Entity/Test'
                    prefix: 'Shared\Entity\Test'
                    alias: Test
```
