### ISSUE TITLE
make:* commands fail on entities using Single Table Inheritance

### ISSUE THREAD

**Issue by IckleChris** [symfony/maker-bundle#146]
I have the following two entities in a Symfony 4.0.6 application (renamed to match the docs for the sake of this issue) using Doctrine's [Single Table Inheritance](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#single-table-inheritance) feature;

```
App\Entity\Person:
  type: entity
  table: person
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 250
      nullable: true
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: person_type
    type: string
    length: 250
  discriminatorMap:
    thread: App\Entity\Employee
    reply: App\Entity\Manager
```

```
App\Entity\Employee:
  type: entity
  table: ~
  fields:
    ...
```

Running, for example `bin/console make:form EmployeeType Employee` presents the following error;

>In DoctrineEntityHelper.php line 67:
  Notice: Undefined offset: 0

The relevant code;

```
$metadata = $this->getEntityMetadata($entityClassName);

if (null !== $metadata) {
    return new DoctrineEntityDetails(
        $metadata->customRepositoryClassName,
        $metadata->identifier[0], // Error line
        $metadata->fieldMappings,
        $this->getFormFieldsFromEntity($metadata)
    );
}
```

Basically, because the entity metadata does not have an ID (as it exists in the parent) it errors. It doesn't look as though the `getIdentifier` method of `DoctrineEntityDetails` is in use anywhere anyway so I'm not sure what the identifier is required for. Temporarily replacing the line causing error results in the form being successfully created as expected. 

If the `make` features can't work without entities having an identifier, it may be worth adding an error to describe that. Thanks!
