### ISSUE TITLE
YamlSourceManipulator adding item to after array leads to bug

### ISSUE THREAD

**Issue by pincher2012** [symfony/maker-bundle#1666]
Example of config:

```yaml
framework:
    messenger:
        routing:
            App\Messages\OldMessage: [ transport1, transport2 ]
===
$data['framework']['messenger']['routing']['App\Messages\NewMessage'] = 'async';
===
framework:
    messenger:
        routing:
            App\Messages\TestMessage: [ transport1, transport2 ]
            App\Messages\NewMessage: async
```

PR with failed test: https://github.com/symfony/maker-bundle/pull/1665
