### ISSUE TITLE
make:entity --regenerate on existing entity class

### ISSUE THREAD

**Issue by manzolo** [symfony/maker-bundle#207]
The command "make:entity --regenerate App" correctly generates the entities (classes) the first time, when there are not yet the classes of the entities.
```
App\Entity\Myentity:
    type: entity
    table: Myentity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO`
    fields:
        existingproperty:
            type: integer
```

If I add a property "newproperty" to the file entityname.orm.yml,

```
App\Entity\Myentity:
    type: entity
    table: Myentity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO`
    fields:
        existingproperty:
            type: integer
        newproperty:
            type: boolean
            nullable: true
```
 when I execute the command I get this error:
> Property App\Entity\Myentity::$newproperty does not exist

The workaround is to add property to the class:
```
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

class Myentity
{

    private $newproperty;
```
In this case, if i run "make:entity --regenerate App", the command correctly generate getter and setter.
It Is a bug or it is correct that it works like that?

Thanks for your work
