### ISSUE TITLE
[SUGGESTION] Override the generated class namespace

### ISSUE THREAD

**Issue by Guikingone** [symfony/maker-bundle#391]
Hi everyone 👋 

Small question about the idea of overriding the namespace which is generated during the construction of every class using the `make:*` command, could it be a good idea to add a configuration key for each namespace? 

Example: 

```yaml
maker:
    root_namespace: 'Acme'
    entity_namespace: 'Acme\Domain'
```

Or maybe something like a `--namespace` option? 🤔 

Thanks for the feedback 🙂  

**Update:** Concerned changes:

```php 
$rootNode
    ->children()
        ->scalarNode('root_namespace')->defaultValue('App')->end()
        ->scalarNode('entity_namespace')->defaultValue('App')->end()
    ->end()
;
```
