### ISSUE TITLE
make:entity thrown could not find driver when relation type

### ISSUE THREAD

**Issue by antoine1003** [symfony/maker-bundle#586]
**Symfony version(s) affected**: 4.4.7

**Description**  
Hi,
I work on a Symfony project that use PostgreSQL as database. A really strange thing happen : when I run `php bin/console make:entity Plane` I can add any field if it's not a relation (string, integer, ...). But when I set type entity in maker it throws an error : 

> In PDOConnection.php line 31:
> could not find driver
> In PDOConnection.php line 27:
> could not find driver

When I run `php bin/console debug:config doctrine --env=dev` it shows the pdo_pgsql driver. I checked in my `php.ini` the `pdo_pgsql` is set, it's confirmed by `php -m`.

Here is the strangest part : `php bin/console make:migrate` and `php bin/console doctrine:migrations:migrate` works perfectly fine...

**How to reproduce**  
My `doctrine.yaml`

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '15.1'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            
            delivery:
                url: '%env(resolve:DELIVERY_DATABASE_URL)%'
                driver: 'sqlsrv'
                charset: UTF-8
```

Thanks
