### ISSUE TITLE
YamlSourceManipulator cannot find original value for multline string

### ISSUE THREAD

**Issue by jon-ht** [symfony/maker-bundle#608]
I'm making my own maker command and I need to update a config file.

The original file looks like this

```yaml
nelmio_api_doc:
    documentation:
        info:
            title: API Title
            description: |
                Symfony 5 project

                Some comments with markdown like [/api/doc/users](/api/doc/users)
                or `/api/doc/{area}`
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
```
In my maker, I have `$manipulator = new YamlSourceManipulator(file_get_contents($path));` which returns me the content above.

When I edit manipulator data, I'm getting this error

```
In YamlSourceManipulator.php line 793:
                                                                     
  Cannot find the original value "Symfony 5 project                  
                                                                     
  Some comments with markdown like [/api/doc/users](/api/doc/users)  
  or `/api/doc/{area}`                                               
  "    
```

If I remove multiline string to have `description: Symfony 5 project`, another error is thrown

```
In YamlSourceManipulator.php line 549:
                                
  Cannot find the key "Bearer"  
                                
```

Do you know if there is a workaround for this ?
