### ISSUE TITLE
make:entity with multiple entity managers

### ISSUE THREAD

**Issue by jacraade** [symfony/maker-bundle#636]
having multiple connections / entity managers like this:

```yaml
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Default:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Default'
                        prefix: 'App\Entity\Default'
                        alias: Default
            sync:
                connection: sync
                mappings:
                    Sync:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Sync'
                        prefix: 'App\Entity\Sync'
                        alias: Sync
```

gets ignored by make:entity and for that reason it cant find existing entities and new entites are created in the root folder and need manual adjustments (move entity into folder, adjust namespace, and the same for the repository)

would be great if it detects multiple connections / entity managers to ask which to use first

version 1.19.0 with symfony 4.4.10

**Comment by velreine** [comment]
php bin/console make:entity Default\MyNewEntity
php bin/console make:entity Sync\MyOtherNewEntity

**Comment by jacraade** [comment]
> php bin/console make:entity Default\MyNewEntity
> php bin/console make:entity Sync\MyOtherNewEntity

i guess that kinda works. yet it still generates some strange things like:

`@ORM\Entity(repositoryClass="App\Repository\Repository")(repositoryClass=TestRepository::class)`

when i create a Sync\Test entity. where it should be:

`@ORM\Entity(repositoryClass="App\Repository\Sync\TestRepository")`

**Comment by jenyak** [comment]
@velreine is there a way to generate in custom directory like `/src/MyNewEntity` ?

**Comment by velreine** [comment]
I'm not associated with the bundle, the commands i supplied are just the one i use which works for me. I use Symfony 5.1 -- when i execute these commands Entities are automatically put into src/Entity/<dir>/<entityName>

when i execute php bin/console make:entity <dir>\<entityname>

I don't know why you owuld want to put your Entities into the root of src though that seems like a bad practice as your project grows.

**Comment by jenyak** [comment]
@velreine thanks for advice. I did not want to move my other entities to from `src/Entity/` to `src/Entity/Default`.
Solve it by rearranging managers in config
```
doctrine:
    orm:
        entity_managers:
            my_new_entities:
            default:
```

this allow keep entitles  from  `default` in `src/Entity/` and  `my_new_entities` in `src/Entity/MyNew/`
