### ISSUE TITLE
Cannot add a key to a second-level hash after a key with empty value in YAML

### ISSUE THREAD

**Issue by andrewmy** [symfony/maker-bundle#678]
Given:
```yaml
volumes:
  abc-data:

networks:
```

Manipulating it with:
```php
$data['volumes']['foo-data'] = 'anything';
```

The expected result is:
```yaml
volumes:
  abc-data:
  foo-data: anything
```

Actual result: `YamlManipulationFailedException` with message `Failed updating YAML contents: the process was successful, but something was not updated. Expected new data: ...`.

The would-be output from the exception message:
```yaml
volumes:
  abc-data:

foo-data: anything
networks:
```

~Failing test case~ Fix PR: https://github.com/symfony/maker-bundle/pull/679

Adding the same key after a key with a non-empty value works as expected.
