### ISSUE TITLE
Support quoted keys in Messenger message classes

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/maker-bundle#894]
Originally reported by @valentinloiseau in https://github.com/symfony/symfony-docs/pull/15400

-----

When creating a message class by running `php bin/console make:message` quotes in YAML keys causes YamlSourceManipulator error if at least one other message is registered:

```bash
In YamlSourceManipulator.php line 581:
                                                    
  Cannot find the key "App\Message\CommentMessage"
```

Original config:

```yaml
# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            routing:            
                'App\Message\CommentMessage': async
```

The pattern `#\bApp\\Message\\CommentMessage( )*:#` provided by `Symfony\Bundle\MakerBundle\Util\YamlSourceManipulator::getKeyRegex` does not match quotes around keys.
