### ISSUE TITLE
[Console] Bug with multiple entity_managers

### ISSUE THREAD

**Issue by inzanty** [symfony/maker-bundle#921]
**Symfony version(s) affected**: 5.3.3

**Description**
I need to define two entity managers and my config looks similar this:
```yaml orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Web:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Web'
                        prefix: 'App\Entity\Web'
                        alias: Web
            stats:
                connection: stats
                mappings:
                    Stats:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Stats'
                        prefix: 'App\Entity\Stats'
                        alias: Stats
```

**How to reproduce**
If execute `php bin/console make:entity` command, i will get this error:
```[ERROR] Only annotation mapping is supported by make:entity, but the
         <info>App\Entity\User</info> class uses a different format. If you would
         like this command to generate the properties & getter/setter methods, add
         your mapping configuration, and then re-run this command with the
         <info>--regenerate</info> flag.
```

**Possible Solution**
Exactly don't know how to fix this problem.

**Additional context**
![Screenshot_11](https://user-images.githubusercontent.com/53940590/124377605-606ed680-dcb5-11eb-95be-e3757fc20dac.png)
