### ISSUE TITLE
New options for strict_types

### ISSUE THREAD

**Issue by upyx** [symfony/maker-bundle#929]
Hi

Using of `declare(strict_types=1);` was offered in #80 and then declined. However, many things have changed since 2017.  The most notable ones are: ending support of [PHP 5](https://www.php.net/supported-versions.php) and accepting the [PSR-12](https://www.php-fig.org/psr/psr-12/) standard that requires strict types. So new Symfony-based projects mostly use PSR and strict types.

It is easy to format code in IDE to any code styles' requirements, but it is so annoying to add `declare(strict_types=1);` again and again... and again...

I suggest adding command options for turning strict types on and off and adding an optional configuration for choosing default behavior.

| Options | Description |
|------------|-----------------|
|`--strict-types`| Add `declare(strict_types=1);` to head of PHP file |
|`--no-strict-types`| Don't add `declare(strict_types=1);` to head of PHP file |

Example of usage:
```
bin/console make:command --strict-types app:make-me-happy
```

Example of configuration:
```yaml
# config/packages/dev/maker.yaml
maker:
    # Add `declare(strict_types=1);` to head of generated PHP file by default
    # default: false
    strict_types: true
```

---

I'm ready to implement that :wink:
