### ISSUE TITLE
[make:entity] Create GraphQL Scaffolder with make:entity command

### ISSUE THREAD

**Issue by manonworld** [symfony/maker-bundle#965]
Can we make GraphQL scaffolding option with ``` make:entity ``` command?

Like so:

``` make:entity EntityName --generate-graphql-scaffold ```

Which should generate a ``` EntityName.yaml ``` file in the directory ``` config/graghql/ ``` contains the following example structure:

```
 EntityName:
    type: object
    config:
        fields:
            id:
                type: 'Int!'
            name:
                type: 'String!'
```

Many thanks for the team
Cheers!
