### ISSUE TITLE
make:entity - ServiceEntityRepositoryInterface - Make sure the service exists and is tagged with "doctrine.repository_service"

### ISSUE THREAD

**Issue by kironet** [symfony/maker-bundle#98]
Hello,

tried command `make:entity Color`
Entity has successfully generated, but getting this error when trying to run website.

> The "App\Repository\ColorRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service".

Generated Repository:

```
<?php

namespace App\Repository;

use App\Entity\Product\Color;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

class ColorRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Color::class);
    }

    /*
    public function findBySomething($value)
    {
        return $this->createQueryBuilder('c')
            ->where('c.something = :value')->setParameter('value', $value)
            ->orderBy('c.id', 'ASC')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult()
        ;
    }
    */
}

```

**Comment by yceruto** [comment]
Hi @kironet, make sure your `ColorRepository` is registered and autowired into `services.yaml`.

**Comment by PayteR** [comment]
Could you @yceruto please provide an example? Thank you.

**Comment by weaverryan** [comment]
It should “just work”. But check your services.yaml file to make sure that the Repository directory is not in the “exclude” for the App\ registration line. If you’re having issues, please post your services.yaml file :)

**Comment by PayteR** [comment]
hm, it's not in excluded

```
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'
```

**Comment by yceruto** [comment]
So I guess it was not auto tagged for some reason, you're using Symfony = 3.3+, right? try manual registration:
```
App\Repository\ColorRepository:
    tags: ['doctrine.repository_service']
```
?

**Comment by PayteR** [comment]
i'm using Symfony 4.0.3 with flex bootstraped just recently, @weaverryan said that it should be automatic, so somewhere is problem and it would be better to solve it rather in Symfony bundles, than do some quick fixes in my project. Here is my whole services.yaml, i can provide anything that could help, just let me know.

```
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

```

**Comment by clem** [comment]
Same problem here... :(

**Comment by 20uf** [comment]
Same here

**Comment by clem** [comment]
I think I found a solution. You have to add `autowire: true` in the repository declaration:

```
App\Repository\ColorRepository:
    autowire: true
    tags: ['doctrine.repository_service']
```

**Comment by tacman** [comment]
It's working for me after I clear and warmup the cache.

**Comment by Enchufadoo** [comment]
Guys, do I have to register every repository manually or is there a way to register all repositories in the folder src/Repository?

**Comment by stof** [comment]
> I think I found a solution. You have to add autowire: true in the repository declaration:

@clem that's weird, as the `services.yaml` of a Flex project already enables autowiring as a file-level default. Have you changed this ?

**Comment by clem** [comment]
@stof No, but I think my error was to set this services in an external file without adding the `_defaults` at the beginning of the file. That's why I found this solution.

**Comment by PayteR** [comment]
@tacman i tried this, but didn't helped, did you update something prior warmup or did something that could fix problem?

**Comment by tacman** [comment]
Like other posts in this thread, I kept trying things until it worked, but
there's absolutely no guarantee that the last thing I tried was the thing
that fixed it.

Sort of just stabbing at things, but it's a new project that was built
pretty much by following a tutorial, so I'm guessing the core team will fix
it at some point -- too many of us are seeing the error for something that
seems like it'd be automatic.

**Comment by kironet** [comment]
Just to be clear, I've never fixed this error. Just went back to old fashion repository file. 
My config is the same as everybody else's, and I really don't want to declare every shingle one repository in my services. :)

**Comment by continga** [comment]
I am having the same issue with a bare new Symfony 4 application - is there any bugfix or workaround available yet? Manually adding the repository class to the services.yaml file did not help

**Comment by continga** [comment]
Okay, some more information:

The error only happens for me when I request a repository directly via Doctrine's EntityManager, so e.g. inside of a controller by `$this->getDoctrine()->getManager()->getRepository(MyEntity::class)`.

The error does *not* happen when I let the service container inject the repository into my service e.g. like this:
```
/**
 * @required
 */
public function setRepo(MyRepo $repo)
{
    $this->repo = $repo;
}
```
I am then able to access the repository directly via $this->repo and everything works.

So the error seems to be related to the Doctrine EntityManager?

**Comment by weaverryan** [comment]
@continga: that’s interesting. What is the error you get exactly? Can you post your services.yaml file, your entity and your repository? And what version of DoctrineBundle do you have?

Enough people are having issues that it seems like there’s an issue, or that something is too easy to mess up.

**Comment by vladciulley** [comment]
@weaverryan, I'm having a related issue on Symfony 4.0.8. Might be the same so I'll write it here.

I'm working on a bundle structured like this:

    \Acme
      \FooBundle
        \Bar
          \Entity
            - Bar.php
          \Repository
            - BarRepository.php
          - BarManager.php
        \Baz
          \Entity
            - Baz.php
          \Repository
            - BazRepository.php
          - BazManager.php
        \Resources
            \config
                - services.yaml

the bundle services configuration:

    # vendor\acme\foo-bundle\Resources\config\services.yaml
    services:
        Acme\FooBundle\:
            resource: '../../*/{*Manager.php,Repository/*Repository.php}'
            autowire: true

In project's services I have:

    services: 
        _defaults:
            autowire: true
            autoconfigure: true
            public: false

With this configuration, when using in controller (just as @continga said in latest answer): 
```$this->getDoctrine()->getRepository(Bar::class)```
 or 
```$this->getDoctrine()->getManager()->getRepository(Bar::class)```, 
it throws an error:

> The "Acme\FooBundle\Bar\Repository\BarRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service".

In console, if I run:

```php bin/console debug:autowiring | grep BarRepository```

I get:

```  Acme\FooBundle\Bar\Repository\BarRepository```

Adding this in bundle config:

    Acme\FooBundle\Bar\Repository\BarRepository\:
        resource: '../../Bar/Repository/BarRepository.php'
        autowire: true
        tags: ['doctrine.repository_service']

before or after the ```Acme\FooBundle\:``` config, does not help (It's pretty difficult to disable the original config to see if it makes any difference, since there are many services interconnected in the project).

Tried to force the tags registration, according to the documentation: https://symfony.com/doc/current/service_container/tags.html#autoconfiguring-tags

by using:

    protected function build(ContainerBuilder $container)
    {
        $container->registerForAutoconfiguration(BarRepository::class)
            ->addTag('doctrine.repository_service')
        ;
    }

Tried to put the ```build()``` method in my bundle class, then in kernel and even in my bundle's extension class (as suggested in the documentation - which I think is wrong), but it just won't work!

**Comment by weaverryan** [comment]
Hey @vladciulley!

I can probably help :). A few things:

1) In your vendor bundle, you are 100% responsible for registering your services. What I mean is, nothing in the app's services.yaml file will have any effect on your services.

2) Typically, it's not a best practice to use service auto-registration, autowiring or autoconfiguration in vendor bundles. To keep things predictable, you should really explicitly configure everything. You don't have to, but that's the best practice :).

3) ONE way or another, you need to give your repository's the `doctrine.repository_service` tag. In an application, this just happens magically because of the `services.yaml` config. In a vendor bundle, it's your job. If you define the services explicitly, just be sure to give each repository service the tag. If you *do* want to use auto-registration, etc, then you should add the `autoconfigure: true` option when "loading" your services. You actually DID this in your final `services.yaml` example above. I don't know why this didn't work, but you're probably very close :). My recommendation (IF you're going to do the auto-registration stuff, is to just have ONE line that auto-registers everything) and have `autoconfigure: true` under it. I noticed that you first seem to auto-register everything, but omit the Repository classes. That may be causing some confusion, and you may be overriding some service definitions later with other auto-registration lines. If you simplify, then your `autoconfigure: true` may start working.

Cheers!

**Comment by chriscadcw** [comment]
Hello, 

So I just ran into this same issue, and I wasn't sure if bumping an old post is the correct thing to do or whether I should create a new one for the same issue.

The error:

```php
The "\App\Repository\MailTemplateRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service".
```

From what I've been able to determine, it is caused by either calling a repository directly, or trying to TypeHint an Entity in a method:

```php
public function show(MailTemplate $mailTemplate): Response
    {
        return $this->render('mail_template/show.html.twig', ['mail_template' => $mailTemplate]);
    }
```
and 
```php
public function show($id): Response
    {
        $mailTemplate = $this->getDoctrine()->getManager()->getRepository (MailTemplate::class)->find($id);
        return $this->render('mail_template/show.html.twig', ['mail_template' => $mailTemplate]);
    }
``` 
both generate the error, however,

```php
public function show(MailTemplateRepository $mailTemplateRepository, $id): Response
    {
        $mailTemplate = $mailTemplateRepository->find ($id);
        return $this->render('mail_template/show.html.twig', ['mail_template' => $mailTemplate]);
    }
```
Does not cause the error.

Some files that may be helpful:
composer.json
```json
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "jms/serializer": "^1.12",
        "knplabs/knp-menu-bundle": "^2.0",
        "sensio/framework-extra-bundle": "^5.2",
        "symfony/asset": "^4.1",
        "symfony/config": "^4.1",
        "symfony/console": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/form": "^4.1",
        "symfony/framework-bundle": "^4.1",
        "symfony/lts": "^4@dev",
        "symfony/orm-pack": "^1.0",
        "symfony/security-bundle": "^4.1",
        "symfony/swiftmailer-bundle": "^3.2",
        "symfony/twig-bundle": "^4.1",
        "symfony/validator": "^4.1",
        "symfony/webpack-encore-pack": "^1.0",
        "symfony/yaml": "^4.1"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.0",
        "symfony/dotenv": "^4.1",
        "symfony/maker-bundle": "^1.5",
        "symfony/profiler-pack": "^1.0",
        "symfony/web-server-bundle": "^4.1"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false
        }
    }
}
```

config/services.yaml
```yaml
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    app.name: 'S.A.V.E. Online Assessment'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # adding the required tag to all repository services
    App\Repository\:
        resource: '../src/Repository'
        autowire: true
        tags: ['doctrine.repository_service']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    app.menu_builder:
        class: App\Helper\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
            - { name: knp_menu.menu_builder, method: createAccountMenu, alias: account }
            - { name: knp_menu.menu_builder, method: createClientMenu, alias: client }
```

While this work around does allow you to use the repositories in your controllers, I don't believe it was intended to be the only way you could use repositories.  

Any feedback would be great.

**Comment by huncwot** [comment]
Hi, I had simillar issue. In my case I had to change this (irrevelant code is removed):

```php
<?php

namespace AppBundle\Entity;

use AppBundle\Repository\ImportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="ImportRepository")
 */
class Import implements ...
```
to this: 
```php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ImportRepository")
 */
class Import implements ...
```
and **had** to clear apcu cache.

**Comment by chriscadcw** [comment]
@huncwot Thank you for your response, however, it is not the repository class that is causing the issue, it is in fact the Doctrine ServiceEntityRepository class that is causing it to break. 

To test this I added the following code to my `service.yaml` file to see if I could manually autowire the missing service dependency.

```
# Tagging the doctrine ServiceEntityRepository for implementation in classes
Doctrine\Bundle\DoctrineBundle\Repository\:
    resource: '../vendor/doctrine/doctrine-bundle/Repository'
    autowire: true
    tags: ['doctrine.repository_service']
```

The results were the following error:

```
Cannot autowire service "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository": argument "$entityClass" of method "__construct()" has no type-hint, you should configure its value explicitly.
```
I don't know exactly what to do to fix this, and this particular issue is being caused by including an `EntityType` form field that is doing it's own query.  

Any ideas on how to fix this issue, I have a client who is waiting for me to finish updating their site and at this point I'm having to start looking at alternatives.

**Comment by Lpu8er** [comment]
@chriscadcw probably a bit late for you, but may help for future references.

This error is also usually obtained if you do not implement the __construct method while extending a ServiceEntityRepository. That means it's probably not related to the maker bundle repository, but more a Doctrine thing.

**Comment by fyrye** [comment]
@chriscadcw you need to override the `__construct` within the repository that extends `ServiceEntityRepository`. See: https://symfony.com/doc/current/doctrine.html#querying-for-objects-the-repository

```php
namespace AppBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use AppBundle\Entity\YourEnity;
use \Doctrine\Common\Persistence\ManagerRegistry;

class YourEntityRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
         parent::__construct($registry, YourEnity::class);
    }

   //....
}
```
```php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
* @ORM\Entity(repositoryClass="AppBundle\Repository\YourEntityRepository")
*/
class YourEntity
{
   //...
}
```

**Comment by BonBonSlick** [comment]
```
  
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Traits,Utils,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

App\Repository\RentalRepository:
    class: 'App\Repository\RentalRepository'
    autowire: true
    public: true
    tags: ['doctrine.repository_service']
```

Same error
