### ISSUE TITLE
make:user & password_hashers: skip password_hashers update if possible

### ISSUE THREAD

**Issue by weaverryan** [symfony/maker-bundle#990]
Hi!

The latest `security-bundle` recipe comes with a security.yaml file containing this out of the box:

```yaml
security:
    # ...

    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
```

And so, when `make:user` is executed (with "yes" for password), we do not need to update the password hasher. In other words, what we do now is this:

```diff
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
+        App\Entity\User:
+            algorithm: auto
```

Those 2 new lines should not be added if `PasswordAuthenticatedUserInterface` is already present, as they are just not needed.
